# install script gpio-setup
.PHONY .SILENT: all
all:
	echo 'use: make prepare or make install'

.PHONY: prepare
prepare:

.PHONY: clean
clean:

.PHONY: install
install:
	install --group=root --owner=root -Dm555 gpio-setup.sh /opt/

